language: c
compiler:
  - gcc
  - clang

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "N3RtUuiCHTBiVYFhnkpLDU3ZIEW77FcfT7k9JawJE1IVX8kQyCGiAL4JtEPe7vQfeYoiXWpB3J0SZCgb9P+ITbjT+2H5828DKOayTnb6ixx0xo4s6OFnOrzil/1NZ1VwDge6vxabwsM2luLZudqe4VdY/XPmkwg0cUvOq+Xb224="
   
addons:
  coverity_scan:
    project:
      name: "liushuyu/DraftBin"
      description: "Build submitted via Travis CI"
    notification_email: liushuyu_011@163.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4 -e CC=${CC}"
    branch_pattern: master
    build_script_url: "https://raw.githubusercontent.com/liushuyu/DraftBin/master/scan_script.sh"
    
    
script:
  - make -j2 -e CC=${CC}  
 # - if [ "${COVERITY_SCAN}" = '1' ]; then eval "$COVERITY_SCAN_BUILD"; else eval "$STANDARD_BUILD_COMMAND"; fi
 #build_script_url
