language: c
sudo: required
dist: trusty
services:
  - docker
script:
  - docker run -e XCODE_USERNAME -e XCODE_PASSWORD -v "$(pwd):/DraftBin" ubuntu:18.04 /bin/bash -ex /DraftBin/osxcross/travis-ci.sh
env:
  global:
    secure: U97zUitUS4FulAQ4UtGRQj4exX7m1kG8z97KcadQi0zWNbB4wieCELlxhJAxasgEvSxcHraI9h7NumDeyYd0pdE1YnXD6RFLFs5p4t6nGE6IE1gcAqFF5Hatp2ut2/V8W2XmWogDhlWxwtOtyRF3dPGUUQoPa07efzs1B39FOCM=
